### ISSUE TITLE
Multi-platform support

### ISSUE THREAD

**Issue by mfncl9991** [BertrandHustle/chdall#1]
Confirmed working under macOS with the following:

brew install rom-tools (installs chdman and all dependencies to system folders)
modifying script to allow chdman (without.exe)

Should work under linux also, assuming rom-tools package available for the running distro.

Request is to make above script modifications to accept both chdman and chdman.exe and update docs for linux/mac support.

**Comment by mfncl9991** [comment]
also, for windows users would be useful to point to a location where chdman.exe can be retrieved (in the docs)

**Comment by BertrandHustle** [comment]
https://github.com/BertrandHustle/chdall/commit/0576ca44b324b6a72bc1adbf4e16180c9729220b
https://github.com/BertrandHustle/chdall/commit/2c2847976b60f0e4c1902c0e0a4f5ad78e29a62d

Above two commits satisfy this requirement.
